### ISSUE TITLE
deal with global and object variable CS errors

### ISSUE THREAD

**Issue by leonstafford** [leonstafford/WordPressURLDetector#2]
```
FILE: ...WordPressURLDetector/src/DetectCategoryPagination.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 31 | ERROR | Variable "wp_rewrite" is not in valid camel caps
    |       | format
    |       | (Squiz.NamingConventions.ValidVariableName.NotCamelCaps)
 41 | ERROR | Variable "wp_rewrite" is not in valid camel caps
    |       | format
    |       | (Squiz.NamingConventions.ValidVariableName.NotCamelCaps)
 41 | ERROR | Member variable "pagination_base" is not in valid camel
    |       | caps format
    |       | (Squiz.NamingConventions.ValidVariableName.MemberNotCamelCaps)
----------------------------------------------------------------------
```
Jó napot, @szepeviktor! Is there a simple way via `phpcs.xml` to exclude certain vars for these sniffs, like we can do with `WordPress.NamingConventions.ValidVariableName`?

**Comment by szepeviktor** [comment]
> "WordPress application"

What an **upgrade**! 🤣

**Comment by szepeviktor** [comment]
So naming it `wpRewrite` is impossible?

**Comment by szepeviktor** [comment]
I see, it is a global...

```php
// phpcs:ignore Squiz.NamingConventions.ValidVariableName.NotCamelCaps
... $wp_rewrite ...
```

**Comment by leonstafford** [comment]
Yeah, starting to feel like solution is to just avoid that at all costs and grab pagination base by other means... Close?

**Comment by szepeviktor** [comment]
WordPress uses a global variable instead of a DI container.

**Comment by leonstafford** [comment]
Looks like `get_option( 'rewrite_rules' )` may be more useful way to determine some URL structures for this repo... I should be OK for now, thanks for coming to rescue again! I'm just doing first pass at this repo adjusting for Codesniffer, then will get to PHPStan and friends next and cry for help when I get stuck :D

**Comment by leonstafford** [comment]
more work to do in design, but CS issue cleared
